# permissions for end users to edit s3objstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: phd-crd-code
    app.kubernetes.io/managed-by: kustomize
  name: s3objstore-editor-role
rules:
- apiGroups:
  - custom.operator.k8.com.learning.k8.com
  resources:
  - s3objstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom.operator.k8.com.learning.k8.com
  resources:
  - s3objstores/status
  verbs:
  - get
