# permissions for end users to view websites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-crd-lab
    app.kubernetes.io/managed-by: kustomize
  name: website-viewer-role
rules:
- apiGroups:
  - websitegroup.example.com
  resources:
  - websites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - websitegroup.example.com
  resources:
  - websites/status
  verbs:
  - get
